project:
  type: website
  output-dir: docs

website:
  title: 'Ersin Yilmaz'
  navbar:
    background: light
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ersiny
      - icon: linkedin
        href: https://www.linkedin.com/in/ersinyilmaz/
listing:
  contents: posts
  sort: 'date desc'

format:
  html:
    theme: cosmo
    css: styles.css
